# Generated by Django 4.2.7 on 2025-12-14 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockstarauthversionone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Password Reset Log',
                'verbose_name_plural': 'Password Reset Logs',
                'db_table': 'stockstarauthversionone_password_reset_logs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='otpverification',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'verification_type', 'is_used'], name='stockstarau_user_id_73bdb1_idx'),
        ),
        migrations.AddField(
            model_name='passwordresetlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresetlog',
            index=models.Index(fields=['user', 'requested_at'], name='stockstarau_user_id_7ff76a_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetlog',
            index=models.Index(fields=['success', 'requested_at'], name='stockstarau_success_2d1e54_idx'),
        ),
    ]
