# Generated by Django 4.2.7 on 2025-12-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyers_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FyersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_verified', models.CharField(default='N', max_length=1)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_verified', models.CharField(default='N', max_length=1)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_created', models.CharField(default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='fyers_auth.fyerstoken')),
            ],
            options={
                'db_table': 'fyers_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
