# Generated by Django 4.2.7 on 2025-12-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'db_table': 'fyers_exchanges',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'db_table': 'fyers_instruments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_code', models.CharField(max_length=50)),
                ('symbol_name', models.CharField(max_length=255)),
                ('fyers_symbol', models.CharField(max_length=100, unique=True)),
                ('isin', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='fyers_historical_data.exchange')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='fyers_historical_data.instrument')),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbols',
                'db_table': 'fyers_symbols',
                'ordering': ['symbol_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('account_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('specific', 'Specific Account')], max_length=20)),
                ('fyers_account_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('result_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('processing_time_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyers_historical_data.exchange')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyers_historical_data.instrument')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyers_historical_data.symbol')),
            ],
            options={
                'verbose_name': 'Historical Data Request',
                'verbose_name_plural': 'Historical Data Requests',
                'db_table': 'fyers_historical_data_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyers_historical_data.exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyers_historical_data.symbol')),
            ],
            options={
                'verbose_name': 'Data Cache',
                'verbose_name_plural': 'Data Cache',
                'db_table': 'fyers_historical_data_cache',
            },
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['exchange', 'instrument', 'is_active'], name='fyers_symbo_exchang_48edfb_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['symbol_code'], name='fyers_symbo_symbol__15dcec_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['fyers_symbol'], name='fyers_symbo_fyers_s_a9569a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('exchange', 'instrument', 'symbol_code')},
        ),
        migrations.AddIndex(
            model_name='historicaldatarequest',
            index=models.Index(fields=['user_email', 'status'], name='fyers_histo_user_em_72e3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatarequest',
            index=models.Index(fields=['status', 'created_at'], name='fyers_histo_status_61a415_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatacache',
            index=models.Index(fields=['expires_at'], name='fyers_histo_expires_fccdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatacache',
            index=models.Index(fields=['symbol', 'date'], name='fyers_histo_symbol__d39daf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicaldatacache',
            unique_together={('exchange', 'symbol', 'date')},
        ),
    ]
